# Generated by Django 4.2.11 on 2024-06-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.IntegerField(default=0, verbose_name='Preparation Time (minutes)'),
        ),
    ]
